import {
    IconHome, IconBuilding, IconUsers, IconClipboardList, IconReceipt,
    IconUserPlus, IconMessageCircle, IconTruckDelivery, IconTicket, IconTools,
    IconCertificate, IconCash, IconHomeCheck, IconRoute, IconFileDescription,
    IconFileText, IconSettings, IconPhoneCall, IconMessageDots
} from '@tabler/icons-react';
import { AdminRole } from './types';

export interface AppNavigationItem {
    id: string;
    path: string;
    label: string;
    icon: React.ReactNode;
    description?: string;
    allowedRoles?: AdminRole[];
    isSidebarLink: boolean;
    isDashboardCard: boolean;
}

export const appNavigationItems: AppNavigationItem[] = [
    {
        id: 'dashboard',
        path: '/dashboard',
        label: 'Dashboard',
        icon: <IconHome size={20} />,
        description: 'View key statistics and overview.',
        isSidebarLink: true,
        isDashboardCard: false,
    },
    {
        id: 'properties',
        path: '/properties',
        label: 'Properties',
        icon: <IconBuilding size={20} />,
        description: 'View & manage all properties.',
        allowedRoles: ['super-admin', 'telecalling-owner-team', 'telecalling-tenant-team', 'marketing-team'],
        isSidebarLink: true,
        isDashboardCard: true,
    },
    {
        id: 'customers',
        path: '/customers',
        label: 'Customers',
        icon: <IconUsers size={20} />,
        description: 'View & manage customer accounts.',
        allowedRoles: ['super-admin', 'telecalling-owner-team', 'telecalling-tenant-team'],
        isSidebarLink: true,
        isDashboardCard: true,
    },
    {
        id: 'interactions',
        path: '/interactions',
        label: 'Customer Interactions',
        icon: <IconMessageCircle size={20} />,
        description: 'Manage customer visits, wishlist.',
        allowedRoles: ['super-admin', 'telecalling-tenant-team'],
        isSidebarLink: true,
        isDashboardCard: true,
    },
    {
        id: 'enquiries',
        path: '/enquiries',
        label: 'Enquiries',
        icon: <IconMessageDots size={20} />,
        description: 'Review homepage owner and tenant enquiries.',
        allowedRoles: ['super-admin', 'telecalling-owner-team', 'telecalling-tenant-team'],
        isSidebarLink: true,
        isDashboardCard: true,
    },
    {
        id: 'mySalesVisits',
        path: '/my-sales-visits',
        label: 'My Sales Visits',
        icon: <IconRoute size={20} />,
        description: 'View your scheduled property visits.',
        allowedRoles: ['super-admin', 'sales-team'],
        isSidebarLink: true,
        isDashboardCard: true,
    },
    {
        id: 'rentalApplications',
        path: '/rental-applications',
        label: 'Rental Applications',
        icon: <IconFileText size={20} />,
        description: 'Manage rental applications from customers.',
        allowedRoles: ['super-admin', 'telecalling-owner-team', 'telecalling-tenant-team', 'accounts-team'],
        isSidebarLink: true,
        isDashboardCard: true,
    },
    {
        id: 'visitPlans',
        path: '/visit-plans',
        label: 'Visit Plans',
        icon: <IconClipboardList size={20} />,
        description: 'Create & manage visit plans for customers.',
        allowedRoles: ['super-admin', 'accounts-team'],
        isSidebarLink: true,
        isDashboardCard: true,
    },
    {
        id: 'contactPlans',
        path: '/contact-plans',
        label: 'Contact Plans',
        icon: <IconPhoneCall size={20} />,
        description: 'Manage owner contact unlock credit packages.',
        allowedRoles: ['super-admin', 'accounts-team'],
        isSidebarLink: true,
        isDashboardCard: true,
    },
    {
        id: 'transactions',
        path: '/transactions',
        label: 'Transactions',
        icon: <IconReceipt size={20} />,
        description: 'View customer payments for visit plans.',
        allowedRoles: ['super-admin', 'accounts-team'],
        isSidebarLink: true,
        isDashboardCard: true,
    },
    {
        id: 'vendors',
        path: '/vendors',
        label: 'Vendors',
        icon: <IconTruckDelivery size={20} />,
        description: 'Manage service vendor information.',
        allowedRoles: ['super-admin', 'accounts-team', 'telecalling-owner-team', 'telecalling-tenant-team'],
        isSidebarLink: true,
        isDashboardCard: true,
    },
    {
        id: 'services',
        path: '/services',
        label: 'Services',
        icon: <IconTools size={20} />,
        description: 'Define available services for vendors.',
        allowedRoles: ['super-admin'],
        isSidebarLink: true,
        isDashboardCard: true,
    },
    {
        id: 'tickets',
        path: '/tickets',
        label: 'Tickets',
        icon: <IconTicket size={20} />,
        description: 'Manage customer support tickets.',
        allowedRoles: ['super-admin', 'telecalling-owner-team', 'telecalling-tenant-team'],
        isSidebarLink: true,
        isDashboardCard: true,
    },
    {
        id: 'managementPlans',
        path: '/management-plans',
        label: 'Mgmt. Plans',
        icon: <IconCertificate size={20} />,
        description: 'Service plans for property management.',
        allowedRoles: ['super-admin', 'accounts-team'],
        isSidebarLink: true,
        isDashboardCard: true,
    },
    {
        id: 'rentRecords',
        path: '/rent-records',
        label: 'Rent Records',
        icon: <IconFileDescription size={20} />,
        description: 'Oversee rent collection and dues.',
        allowedRoles: ['super-admin', 'accounts-team'],
        isSidebarLink: true,
        isDashboardCard: true,
    },
    {
        id: 'rentPayments',
        path: '/rent-payments',
        label: 'Payments Overview',
        icon: <IconCash size={20} />,
        description: 'View summary of rent payments.',
        allowedRoles: ['super-admin', 'accounts-team'],
        isSidebarLink: true,
        isDashboardCard: true,
    },
    {
        id: 'occupancyStatus',
        path: '/occupancy-status',
        label: 'Occupancy',
        icon: <IconHomeCheck size={20} />,
        description: 'Track property occupancy and rent status.',
        allowedRoles: ['super-admin', 'accounts-team'],
        isSidebarLink: true,
        isDashboardCard: true,
    },
    {
        id: 'admins',
        path: '/admins',
        label: 'Admins',
        icon: <IconUserPlus size={20} />,
        description: 'Manage admin user accounts and roles.',
        allowedRoles: ['super-admin'],
        isSidebarLink: true,
        isDashboardCard: true,
    },
    {
        id: 'homepageSettings',
        path: '/homepage-settings',
        label: 'Homepage Settings',
        icon: <IconSettings size={20} />,
        description: 'Manage content & images of the client website homepage.',
        allowedRoles: ['super-admin'],
        isSidebarLink: true,
        isDashboardCard: true,
    },
];
